const USER_CREATE = "USER_CREATE";
const USER_DELETE = "USER_DELETE";
const INFORMATION_CREATE = "INFORMATION_CREATE";
const SHOW_PATCH = "SHOW_PATCH";

export {
  USER_CREATE,
  USER_DELETE,
  INFORMATION_CREATE,
  SHOW_PATCH
};
