const USER_CREATE = "USER_CREATE";
const USER_DELETE = "USER_DELETE";
const INFORMATION_CREATE = "INFORMATION_CREATE";
const SHOW_PATCH = "SHOW_PATCH";
const CHAT_PATCH_MSG = "CHAT_PATCH_MSG";
const CHAT_PATCH_ONLINEUSER = "CHAT_PATCH_ONLINEUSER";
const CHAT_PATCH_MSGS = "CHAT_PATCH_MSGS";

export {
  USER_CREATE,
  USER_DELETE,
  INFORMATION_CREATE,
  SHOW_PATCH,
  CHAT_PATCH_MSG,
  CHAT_PATCH_ONLINEUSER,
  CHAT_PATCH_MSGS
};
