const USER_CREATE = "USER_CREATE";
const USER_DELETE = "USER_DELETE";
const INFORMATION_CREATE = "INFORMATION_CREATE";
const INFORMATION_LEAVEMSG = "INFORMATION_LEAVEMSG";
const SHOW_PATCH = "SHOW_PATCH";
const CHAT_PATCH_MSG = "CHAT_PATCH_MSG";
const CHAT_PATCH_ONLINEUSER = "CHAT_PATCH_ONLINEUSER";
const CHAT_PATCH_MSGS = "CHAT_PATCH_MSGS";
const SPIDER_CREATE_ORIGINMAP = "SPIDER_CREATE_ORIGINMAP";
const SPIDER_PATCH_JOBS = "SPIDER_PATCH_JOBS";
const SPIDER_PATCH_ADDRLIST = "SPIDER_PATCH_ADDRLIST";
const VISIT_PATCH_VISITS = "VISIT_PATCH_VISITS";
const VISIT_PATCH_VOTE = "VISIT_PATCH_VOTE";
const VISIT_PATCH_LEAVEMSGS = "VISIT_PATCH_LEAVEMSGS";
const VISIT_PATCH_VOTETIMES = "VISIT_PATCH_VOTETIMES";

export {
  USER_CREATE,
  USER_DELETE,
  INFORMATION_CREATE,
  INFORMATION_LEAVEMSG,
  SHOW_PATCH,
  CHAT_PATCH_MSG,
  CHAT_PATCH_ONLINEUSER,
  CHAT_PATCH_MSGS,
  SPIDER_CREATE_ORIGINMAP,
  SPIDER_PATCH_JOBS,
  SPIDER_PATCH_ADDRLIST,
  VISIT_PATCH_VISITS,
  VISIT_PATCH_VOTE,
  VISIT_PATCH_LEAVEMSGS,
  VISIT_PATCH_VOTETIMES
};
